Auth_Project/Auth_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import base


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base, name='base'),
    path('users/', include('users.urls', namespace='users')),
]

Auth_Project/users/urls.py
from django.urls import path

from .views import login, registration
app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
]

Auth_Project/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

Auth_Project/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput())
    password = forms.CharField(label='Password', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput())
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

Auth_Project/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse

from .forms import UserLoginForm, UserRegistrationForm


def base(request):
    return render(request, 'users/base.html')


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                messages.success(request, 'Успешный вход!')
                return HttpResponseRedirect(reverse('base'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Вы успешно зарегистрированы!')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/registration.html', context)

Auth_Project/users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav>
    <ul>
        <li><a href="{% url 'users:login' %}">Login</a></li>
        <li><a href="{% url 'users:registration' %}">Register</a></li>
    </ul>
  </nav>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

Auth_Project/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

Auth_Project/users/templates/users/registration.html
{% extends 'users/base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
{% endblock %}